version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      backend-python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
