[mypy]
python_version = 3.13
warn_unused_ignores = True
warn_redundant_casts = True
check_untyped_defs = True
no_implicit_optional = True

[mypy-aiosqlite.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-apscheduler.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-ldap3.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-msal.*]
ignore_missing_imports = True
follow_imports = skip
