target-version = "py312"
line-length = 120
exclude = [
  "alembic",
  "tests",
  "app/tests",
  "scripts",
  "venv",
  "coverage_html",
  "logs",
]

[lint]
select = ["E", "F", "W", "I"]

[lint.per-file-ignores]
"alembic/versions/*.py" = ["E", "F", "W", "I"]
"app/models/__init__.py" = ["F401"]
