import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
    Save,
    X,
    ChevronRight,
    ChevronLeft,
    AlertCircle,
    Info,
    User,
    Star,
    Activity,
    Plus,
    Clock,
    CheckCircle
} from 'lucide-react';
import { useTranslation } from '@/i18n/hooks';
import { StepIndicator } from '@/components/ui/StepIndicator';
import { riskApi } from '@/services/riskApi';
import { ApiClientError } from '@/services/apiClient';
import { lookupApi } from '@/services/lookupApi';
import type { UserLookupItem } from '@/services/lookupApi';
import type { Risk, RiskCreate, RiskUpdate } from '@/types/risk';
import { RiskStatus } from '@/types/risk';
import { RiskScoreMatrix } from '@/components/RiskScoreMatrix';
import { useRiskTypes, useTotalAssetsValue, useRiskThresholds } from '@/hooks/useRiskHubConfig';
import { ThemedSelect } from '@/components/ui/ThemedSelect';
import {
    PROBABILITY_DESCRIPTIONS,
    IMPACT_DESCRIPTIONS,
    formatFinancialRange
} from '@/constants/riskScoreDescriptions';
import { parseUpdateResult } from '@/lib/approvalUi';

interface RiskFormProps {
    initialData?: Risk;
    isEdit?: boolean;
}

export function RiskForm({ initialData, isEdit = false }: RiskFormProps) {
    const navigate = useNavigate();
    const { t } = useTranslation(['risks', 'common', 'errorKeys', 'approvals']);
    const steps = [
        { id: 'identity', title: t('risks:form.steps.identity'), icon: Info },
        { id: 'ownership', title: t('risks:form.steps.ownership'), icon: User },
        { id: 'scoring', title: t('risks:form.steps.scoring'), icon: Activity },
    ];
    const [currentStep, setCurrentStep] = useState(0);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Approval-queued state for edit flows (HTTP 202)
    const [approvalQueued, setApprovalQueued] = useState<{ id: number; message: string } | null>(null);

    // Fetch risk types from Risk Hub
    const { riskTypes, isLoading: riskTypesLoading } = useRiskTypes();

    // Fetch total assets for financial loss calculations
    const { totalAssets } = useTotalAssetsValue();

    // Get thresholds for score-based colors
    const { thresholds } = useRiskThresholds();

    // Helper to get text color class based on score
    const getScoreTextColor = (score: number) => {
        if (score >= thresholds.critical) return 'text-rose-400';
        if (score >= thresholds.high) return 'text-orange-400';
        if (score >= thresholds.medium) return 'text-amber-400';
        return 'text-emerald-400';
    };

    // Helper to get slider accent color based on score
    const getSliderAccent = (score: number) => {
        if (score >= thresholds.critical) return 'accent-rose-500';
        if (score >= thresholds.high) return 'accent-orange-500';
        if (score >= thresholds.medium) return 'accent-amber-500';
        return 'accent-emerald-500';
    };

    // Validation errors (inline)
    const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

    interface DepartmentLookup {
        id: number;
        name: string;
        code?: string;
    }

    // Lookups
    const [users, setUsers] = useState<UserLookupItem[]>([]);
    const [departments, setDepartments] = useState<DepartmentLookup[]>([]);
    const [existingProcesses, setExistingProcesses] = useState<string[]>([]);
    const [existingCategories, setExistingCategories] = useState<string[]>([]);
    const [subprocessesByProcess, setSubprocessesByProcess] = useState<Record<string, string[]>>({});
    const [showProcessDropdown, setShowProcessDropdown] = useState(false);
    const [showSubprocessDropdown, setShowSubprocessDropdown] = useState(false);
    const [showCategoryDropdown, setShowCategoryDropdown] = useState(false);

    // Owner search/filter
    const [ownerSearch, setOwnerSearch] = useState('');
    const [roleFilter, setRoleFilter] = useState<string>('');

    const [formData, setFormData] = useState<Partial<Risk>>(() => ({
        // risk_id_code is auto-generated by backend
        name: '',
        process: '',
        subprocess: '',
        risk_type: initialData?.risk_type || 'operational',
        category: '',
        description: '',
        status: RiskStatus.ACTIVE,
        is_priority: false,
        gross_probability: 3,
        gross_impact: 3,
        net_probability: 2,
        net_impact: 2,
        kri_indicator: '',
        kri_threshold_green: '',
        kri_threshold_yellow: '',
        kri_threshold_red: '',
        ...initialData
    }));

    useEffect(() => {
        const loadLookups = async () => {
            try {
                const [userData, deptData, risksData] = await Promise.all([
                    lookupApi.getUsers(),
                    lookupApi.getDepartments(),
                    riskApi.getRisks({ skip: 0, limit: 100 })
                ]);
                setUsers(userData);
                setDepartments(deptData);

                // Extract unique process names
                type RiskItem = { process?: string; subprocess?: string; category?: string };
                const processes = [...new Set(risksData.items.map((r: RiskItem) => r.process).filter(Boolean))];
                setExistingProcesses(processes as string[]);

                // Extract unique categories
                const categories = [...new Set(risksData.items.map((r: RiskItem) => r.category).filter(Boolean))];
                setExistingCategories(categories as string[]);

                // Build subprocess map by process
                const subprocMap: Record<string, string[]> = {};
                risksData.items.forEach((r: RiskItem) => {
                    if (r.process && r.subprocess) {
                        if (!subprocMap[r.process]) subprocMap[r.process] = [];
                        if (!subprocMap[r.process].includes(r.subprocess)) {
                            subprocMap[r.process].push(r.subprocess);
                        }
                    }
                });
                setSubprocessesByProcess(subprocMap);
            } catch (err) {
                console.error('Failed to load lookups:', err);
            }
        };
        loadLookups();
    }, []);

    const handleInputChange = (field: keyof Risk, value: unknown) => {
        setFormData(prev => {
            const newData = { ...prev, [field]: value };

            // Auto-fill department when owner is selected
            if (field === 'owner_id' && value) {
                const selectedUser = users.find(u => u.id === value);
                if (selectedUser?.department_id) {
                    newData.department_id = selectedUser.department_id;
                }
            }

            return newData;
        });

        // Clear errors outside of setFormData to avoid stale closure
        setFieldErrors(prev => {
            const newErrors = { ...prev };
            if (prev[field]) {
                newErrors[field] = '';
            }
            // Also clear department error when auto-filled
            if (field === 'owner_id' && prev.department_id) {
                newErrors.department_id = '';
            }
            return newErrors;
        });
    };

    // Validate Step 1: Identity
    const validateStep1 = (): boolean => {
        const errors: Record<string, string> = {};

        if (!formData.name?.trim()) {
            errors.name = 'Risk Name is required';
        }
        if (!formData.process?.trim()) {
            errors.process = 'Main Process is required';
        }
        if (!formData.category?.trim()) {
            errors.category = 'Category is required';
        }
        if (!formData.description?.trim()) {
            errors.description = 'Risk Description is required';
        }

        setFieldErrors(errors);
        return Object.keys(errors).length === 0;
    };

    // Validate Step 2: Details & Owner
    const validateStep2 = (): boolean => {
        const errors: Record<string, string> = {};

        if (!formData.department_id) {
            errors.department_id = 'Department is required';
        }
        if (!formData.owner_id) {
            errors.owner_id = 'Risk Owner is required';
        }

        setFieldErrors(errors);
        return Object.keys(errors).length === 0;
    };

    // Filtered users based on search, role, AND department
    const filteredUsers = users.filter(user => {
        const matchesSearch = !ownerSearch ||
            user.name?.toLowerCase().includes(ownerSearch.toLowerCase()) ||
            user.email?.toLowerCase().includes(ownerSearch.toLowerCase());
        const matchesRole = !roleFilter || user.role_name === roleFilter;
        // If department is selected, filter to that department's users
        const matchesDepartment = !formData.department_id || user.department_id === formData.department_id;
        return matchesSearch && matchesRole && matchesDepartment;
    });

    // Get unique roles for filter - role is an object with name property
    const uniqueRoles: string[] = [...new Set(users.map(u => u.role_name).filter((r): r is string => !!r))];

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Validate all steps before submission
        if (!validateStep1()) {
            setCurrentStep(0);
            return;
        }
        if (!validateStep2()) {
            setCurrentStep(1);
            return;
        }

        try {
            setIsSubmitting(true);
            setError(null);
            setApprovalQueued(null);

            if (isEdit && initialData) {
                const result = await riskApi.updateRisk(initialData.id, formData as RiskUpdate);
                // Use standardized helper to check for 202 approval-queued response
                const parsed = parseUpdateResult(result);
                if (parsed.kind === 'approval') {
                    setApprovalQueued({
                        id: parsed.approvalId,
                        message: parsed.message,
                    });
                    setIsSubmitting(false);
                    return; // Stay on form, don't navigate
                }
            } else {
                const newRisk = await riskApi.createRisk(formData as RiskCreate);
                navigate(`/risks/${newRisk.id}`);
                return;
            }

            navigate(`/risks/${initialData?.id}`);
        } catch (err: unknown) {
            console.error('Error saving risk:', err);
            if (err instanceof ApiClientError) {
                setError(err.messageKey);
            } else {
                setError('errorKeys.save_risk_failed');
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    const nextStep = (e?: React.MouseEvent) => {
        if (e) {
            e.preventDefault();
            e.stopPropagation();
        }
        // Validate current step before proceeding
        if (currentStep === 0 && !validateStep1()) return;
        if (currentStep === 1 && !validateStep2()) return;
        setCurrentStep(prev => Math.min(prev + 1, steps.length - 1));
    };
    const prevStep = () => setCurrentStep(prev => Math.max(prev - 1, 0));

    return (
        <form onSubmit={handleSubmit} className="space-y-8 max-w-4xl mx-auto">
            {/* Multi-step indicator */}
            <StepIndicator
                steps={steps}
                currentStep={currentStep}
                isStepClickable={(idx) => isEdit || idx < currentStep}
                onStepClick={(idx) => setCurrentStep(idx)}
            />

            <div className="glass-card min-h-[480px] flex flex-col">
                {/* Approval-queued banner */}
                {approvalQueued && (
                    <div className="mb-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-start gap-3 animate-in fade-in slide-in-from-top-2">
                        <Clock className="h-5 w-5 text-amber-400 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                            <p className="text-amber-200 text-sm font-medium">
                                {t('approval_submitted', { ns: 'errorKeys' })} (ID: {approvalQueued.id})
                            </p>
                            <p className="text-amber-400/80 text-xs mt-1">
                                {approvalQueued.message.startsWith('errorKeys.') ? t(approvalQueued.message, { ns: 'errorKeys' }) : approvalQueued.message}
                            </p>
                            <div className="mt-3 flex gap-3">
                                <Link
                                    to="/approvals"
                                    className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-300 hover:text-amber-100 transition-colors"
                                >
                                    <CheckCircle className="h-3.5 w-3.5" />
                                    {t('common:actions.view')} {t('approvals:title', { ns: 'approvals', defaultValue: 'Approvals' })}
                                </Link>
                                <button
                                    type="button"
                                    onClick={() => setApprovalQueued(null)}
                                    className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
                                >
                                    {t('common:actions.close')}
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {error && (
                    <div className="mb-6 p-4 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-center gap-3 text-rose-400 text-sm font-medium">
                        <AlertCircle className="h-5 w-5" />
                        {error.startsWith('errorKeys.') ? t(error, { ns: 'errorKeys' }) : error}
                    </div>
                )}

                <div className="flex-1 space-y-6">
                    {/* Step 1: Identity */}
                    {currentStep === 0 && (
                        <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                            {/* Risk Name - Primary identifier */}
                            <div>
                                <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                    {t('risks:fields.name')} <span className="text-rose-400">*</span>
                                </label>
                                <input
                                    type="text"
                                    value={formData.name || ''}
                                    onChange={(e) => handleInputChange('name', e.target.value)}
                                    className={`w-full bg-white/5 border rounded-xl px-4 py-3 text-white outline-none focus:border-accent/50 transition-all ${fieldErrors.name ? 'border-rose-500' : 'border-white/10'
                                        }`}
                                    placeholder={t('form.placeholders.name')}
                                />
                                {fieldErrors.name && (
                                    <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                        <AlertCircle className="h-3 w-3" /> {fieldErrors.name}
                                    </p>
                                )}
                            </div>
                            <div className="grid md:grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">{t('risks:form.labels.risk_type')}</label>
                                    <ThemedSelect
                                        value={formData.risk_type || 'operational'}
                                        onValueChange={(v) => handleInputChange('risk_type', v)}
                                        disabled={riskTypesLoading}
                                        className="w-full"
                                        options={riskTypes.map(rt => ({ value: rt.code, label: rt.display_name }))}
                                    />
                                </div>
                                <div className="relative">
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                        {t('risks:form.labels.main_process')} <span className="text-rose-400">*</span>
                                    </label>
                                    <div className="relative">
                                        <input
                                            type="text"
                                            value={formData.process}
                                            onChange={(e) => {
                                                handleInputChange('process', e.target.value);
                                                setShowProcessDropdown(true);
                                            }}
                                            onFocus={() => setShowProcessDropdown(true)}
                                            onBlur={() => setTimeout(() => setShowProcessDropdown(false), 150)}
                                            className={`w-full bg-white/5 border rounded-xl px-4 py-3 text-white outline-none focus:border-accent/50 transition-all ${fieldErrors.process ? 'border-rose-500' : 'border-white/10'
                                                }`}
                                            placeholder={t('form.placeholders.type_or_select')}
                                        />
                                        {/* Dropdown with existing processes */}
                                        {showProcessDropdown && existingProcesses.length > 0 && (
                                            <div className="absolute z-20 top-full left-0 right-0 mt-1 max-h-48 overflow-y-auto rounded-xl border border-white/10 bg-slate-900/95 backdrop-blur-sm divide-y divide-white/5">
                                                {existingProcesses
                                                    .filter(p => !formData.process || p.toLowerCase().includes(formData.process.toLowerCase()))
                                                    .map(process => (
                                                        <button
                                                            key={process}
                                                            type="button"
                                                            onMouseDown={(e) => e.preventDefault()}
                                                            onClick={() => {
                                                                handleInputChange('process', process);
                                                                setShowProcessDropdown(false);
                                                            }}
                                                            className="w-full px-4 py-2.5 text-left text-sm text-white hover:bg-white/10 transition-colors"
                                                        >
                                                            {process}
                                                        </button>
                                                    ))}
                                                {formData.process && !existingProcesses.includes(formData.process) && (
                                                    <div className="px-4 py-2.5 text-xs text-slate-400 flex items-center gap-2">
                                                        <Plus className="h-3 w-3" />
                                                        {t('risks:form.labels.create_value', { value: formData.process })}
                                                    </div>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                    {fieldErrors.process && (
                                        <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                            <AlertCircle className="h-3 w-3" /> {fieldErrors.process}
                                        </p>
                                    )}
                                </div>
                            </div>
                            <div className="grid md:grid-cols-2 gap-6">
                                <div className="relative">
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">{t('risks:form.labels.subprocess_optional')}</label>
                                    <div className="relative">
                                        <input
                                            type="text"
                                            value={formData.subprocess || ''}
                                            onChange={(e) => {
                                                handleInputChange('subprocess', e.target.value);
                                                setShowSubprocessDropdown(true);
                                            }}
                                            onFocus={() => setShowSubprocessDropdown(true)}
                                            onBlur={() => setTimeout(() => setShowSubprocessDropdown(false), 150)}
                                            className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white outline-none focus:border-accent/50 transition-all"
                                            placeholder={formData.process ? t('form.placeholders.subprocess_of', { process: formData.process }) : t('form.placeholders.select_process_first')}
                                        />
                                        {/* Dropdown with subprocesses for selected process */}
                                        {showSubprocessDropdown && formData.process && (subprocessesByProcess[formData.process]?.length || formData.subprocess) && (
                                            <div className="absolute z-20 top-full left-0 right-0 mt-1 max-h-40 overflow-y-auto rounded-xl border border-white/10 bg-slate-900/95 backdrop-blur-sm divide-y divide-white/5">
                                                {(subprocessesByProcess[formData.process] || [])
                                                    .filter(s => !formData.subprocess || s.toLowerCase().includes(formData.subprocess.toLowerCase()))
                                                    .map(subprocess => (
                                                        <button
                                                            key={subprocess}
                                                            type="button"
                                                            onMouseDown={(e) => e.preventDefault()}
                                                            onClick={() => {
                                                                handleInputChange('subprocess', subprocess);
                                                                setShowSubprocessDropdown(false);
                                                            }}
                                                            className="w-full px-4 py-2.5 text-left text-sm text-white hover:bg-white/10 transition-colors"
                                                        >
                                                            {subprocess}
                                                        </button>
                                                    ))}
                                                {formData.subprocess && !(subprocessesByProcess[formData.process] || []).includes(formData.subprocess) && (
                                                    <div className="px-4 py-2.5 text-xs text-slate-400 flex items-center gap-2">
                                                        <Plus className="h-3 w-3" />
                                                        {t('risks:form.labels.create_value', { value: formData.subprocess })}
                                                    </div>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                </div>
                                <div className="relative">
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                        {t('common:labels.category')} <span className="text-rose-400">*</span>
                                    </label>
                                    <div className="relative">
                                        <input
                                            type="text"
                                            value={formData.category || ''}
                                            onChange={(e) => {
                                                handleInputChange('category', e.target.value);
                                                setShowCategoryDropdown(true);
                                            }}
                                            onFocus={() => setShowCategoryDropdown(true)}
                                            onBlur={() => setTimeout(() => setShowCategoryDropdown(false), 150)}
                                            className={`w-full bg-white/5 border rounded-xl px-4 py-3 text-white outline-none focus:border-accent/50 transition-all ${fieldErrors.category ? 'border-rose-500' : 'border-white/10'
                                                }`}
                                            placeholder={t('form.placeholders.type_or_select')}
                                        />
                                        {/* Dropdown with existing categories */}
                                        {showCategoryDropdown && existingCategories.length > 0 && (
                                            <div className="absolute z-20 top-full left-0 right-0 mt-1 max-h-40 overflow-y-auto rounded-xl border border-white/10 bg-slate-900/95 backdrop-blur-sm divide-y divide-white/5">
                                                {existingCategories
                                                    .filter(c => !formData.category || c.toLowerCase().includes(formData.category.toLowerCase()))
                                                    .map(category => (
                                                        <button
                                                            key={category}
                                                            type="button"
                                                            onMouseDown={(e) => e.preventDefault()}
                                                            onClick={() => {
                                                                handleInputChange('category', category);
                                                                setShowCategoryDropdown(false);
                                                            }}
                                                            className="w-full px-4 py-2.5 text-left text-sm text-white hover:bg-white/10 transition-colors"
                                                        >
                                                            {category}
                                                        </button>
                                                    ))}
                                                {formData.category && !existingCategories.includes(formData.category) && (
                                                    <div className="px-4 py-2.5 text-xs text-slate-400 flex items-center gap-2">
                                                        <Plus className="h-3 w-3" />
                                                        {t('risks:form.labels.create_value', { value: formData.category })}
                                                    </div>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                    {fieldErrors.category && (
                                        <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                            <AlertCircle className="h-3 w-3" /> {fieldErrors.category}
                                        </p>
                                    )}
                                </div>
                            </div>
                            <div>
                                <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                    {t('risks:form.labels.risk_description')} <span className="text-rose-400">*</span>
                                </label>
                                <textarea
                                    rows={3}
                                    value={formData.description}
                                    onChange={(e) => handleInputChange('description', e.target.value)}
                                    className={`w-full bg-white/5 border rounded-xl px-4 py-3 text-white outline-none focus:border-accent/50 transition-all resize-none ${fieldErrors.description ? 'border-rose-500' : 'border-white/10'
                                        }`}
                                    placeholder={t('form.placeholders.description')}
                                />
                                {fieldErrors.description && (
                                    <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                        <AlertCircle className="h-3 w-3" /> {fieldErrors.description}
                                    </p>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Step 2: Details & Ownership */}
                    {currentStep === 1 && (
                        <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                            <div className="grid md:grid-cols-2 gap-6">
                                <div>
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                        {t('common:labels.department')} <span className="text-rose-400">*</span>
                                    </label>
                                    <ThemedSelect
                                        value={formData.department_id?.toString() ?? ''}
                                        onValueChange={(v) => handleInputChange('department_id', v ? parseInt(v) : null)}
                                        placeholder={t('form.placeholders.select_department')}
                                        allowEmpty
                                        emptyLabel={t('form.placeholders.select_department')}
                                        className={fieldErrors.department_id ? 'border-rose-500' : ''}
                                        options={departments.map(d => ({ value: d.id.toString(), label: `${d.name} (${d.code})` }))}
                                    />
                                    {fieldErrors.department_id && (
                                        <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                            <AlertCircle className="h-3 w-3" /> {fieldErrors.department_id}
                                        </p>
                                    )}
                                </div>
                                <div>
                                    <label className="block text-[10px] font-black text-slate-500 uppercase tracking-widest mb-2">
                                        {t('risks:fields.owner')} <span className="text-rose-400">*</span>
                                    </label>
                                    {/* Role filter chips + search */}
                                    <div className="flex flex-wrap gap-1.5 mb-3">
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setRoleFilter('');
                                                handleInputChange('owner_id', null);
                                            }}
                                            className={`px-2.5 py-1 text-xs rounded-lg transition-all ${!roleFilter
                                                ? 'bg-accent text-white'
                                                : 'bg-white/5 text-slate-400 hover:bg-white/10'
                                                }`}
                                        >
                                            All
                                        </button>
                                        {uniqueRoles.map(role => (
                                            <button
                                                key={role}
                                                type="button"
                                                onClick={() => {
                                                    setRoleFilter(role);
                                                    // Clear department filter when selecting role
                                                    // Find all users with this role (not filtered by department)
                                                    const usersWithRole = users.filter(u => u.role_name === role);
                                                    // Auto-select if only one user, else clear owner
                                                    if (usersWithRole.length === 1) {
                                                        handleInputChange('owner_id', usersWithRole[0].id);
                                                        // Department will auto-fill via handleInputChange
                                                    } else {
                                                        handleInputChange('owner_id', null);
                                                        handleInputChange('department_id', null);
                                                    }
                                                }}
                                                className={`px-2.5 py-1 text-xs rounded-lg transition-all capitalize ${roleFilter === role
                                                    ? 'bg-accent text-white'
                                                    : 'bg-white/5 text-slate-400 hover:bg-white/10'
                                                    }`}
                                            >
                                                {role}
                                            </button>
                                        ))}
                                    </div>
                                    {/* Selected user or user list */}
                                    {formData.owner_id ? (
                                        <div className={`flex items-center justify-between bg-accent/10 border rounded-xl px-4 py-3 ${fieldErrors.owner_id ? 'border-rose-500' : 'border-accent/30'
                                            }`}>
                                            <div>
                                                <p className="text-sm font-medium text-white">
                                                    {users.find(u => u.id === formData.owner_id)?.name}
                                                </p>
                                                <p className="text-xs text-slate-400">
                                                    {users.find(u => u.id === formData.owner_id)?.role_name}
                                                </p>
                                            </div>
                                            <button
                                                type="button"
                                                onClick={() => handleInputChange('owner_id', null)}
                                                className="text-slate-400 hover:text-white p-1"
                                            >
                                                <X className="h-4 w-4" />
                                            </button>
                                        </div>
                                    ) : (
                                        <div className="space-y-2">
                                            <input
                                                type="text"
                                                placeholder={t('form.placeholders.search_by_name')}
                                                value={ownerSearch}
                                                onChange={(e) => setOwnerSearch(e.target.value)}
                                                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white outline-none focus:border-accent/50 transition-all"
                                            />
                                            <div className={`max-h-40 overflow-y-auto rounded-xl border divide-y divide-white/5 ${fieldErrors.owner_id ? 'border-rose-500' : 'border-white/10'
                                                }`}>
                                                {filteredUsers.length === 0 ? (
                                                    <p className="px-4 py-3 text-sm text-slate-500">{t('common:empty.no_users_found')}</p>
                                                ) : (
                                                    filteredUsers.slice(0, 8).map(u => (
                                                        <button
                                                            key={u.id}
                                                            type="button"
                                                            onClick={() => handleInputChange('owner_id', u.id)}
                                                            className="w-full px-4 py-2.5 flex items-center justify-between hover:bg-white/5 transition-colors"
                                                        >
                                                            <span className="text-sm text-white">{u.name}</span>
                                                            <span className="text-xs text-slate-500 capitalize">{u.role_name}</span>
                                                        </button>
                                                    ))
                                                )}
                                            </div>
                                        </div>
                                    )}
                                    {fieldErrors.owner_id && (
                                        <p className="text-rose-400 text-xs mt-1.5 flex items-center gap-1">
                                            <AlertCircle className="h-3 w-3" /> {fieldErrors.owner_id}
                                        </p>
                                    )}
                                </div>
                            </div>
                            <div className="flex items-center gap-3">
                                <label className="flex items-center gap-3 cursor-pointer group">
                                    <div className={`relative w-12 h-6 rounded-full transition-all ${formData.is_priority ? 'bg-accent' : 'bg-white/10'}`}>
                                        <input
                                            type="checkbox"
                                            className="sr-only"
                                            checked={formData.is_priority}
                                            onChange={(e) => handleInputChange('is_priority', e.target.checked)}
                                        />
                                        <div className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${formData.is_priority ? 'translate-x-6' : 'translate-x-0'}`} />
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <Star className={`h-4 w-4 ${formData.is_priority ? 'text-amber-400 fill-amber-400' : 'text-slate-500'}`} />
                                        <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest group-hover:text-slate-300 transition-colors">{t('risks:fields.is_priority')}</span>
                                    </div>
                                </label>
                            </div>
                        </div>
                    )}

                    {/* Step 3: Scoring */}
                    {currentStep === 2 && (
                        <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                            <div className="grid md:grid-cols-2 gap-12">
                                <section className="space-y-6">
                                    <h4 className={`text-[10px] font-black uppercase tracking-widest ${getScoreTextColor((formData.gross_probability || 1) * (formData.gross_impact || 1))}`}>{t('risks:fields.gross_score')} ({t('risks:scoring.inherent_risk')})</h4>
                                    <div className="space-y-4">
                                        <div>
                                            <label className="flex justify-between text-[10px] font-bold text-slate-500 uppercase mb-2">
                                                <span>{t('risks:fields.probability')}</span>
                                                <span className="text-white">{formData.gross_probability} / 5</span>
                                            </label>
                                            <input
                                                type="range" min="1" max="5" step="1"
                                                value={formData.gross_probability}
                                                onChange={(e) => handleInputChange('gross_probability', parseInt(e.target.value))}
                                                className={`w-full ${getSliderAccent((formData.gross_probability || 1) * (formData.gross_impact || 1))}`}
                                            />
                                            {formData.gross_probability && PROBABILITY_DESCRIPTIONS[formData.gross_probability] && (
                                                <p className="text-xs text-slate-400 mt-1">
                                                    <span className={`font-semibold ${getScoreTextColor((formData.gross_probability || 1) * (formData.gross_impact || 1))}`}>
                                                        {t(PROBABILITY_DESCRIPTIONS[formData.gross_probability].labelKey, PROBABILITY_DESCRIPTIONS[formData.gross_probability].labelKey)}
                                                    </span>
                                                    <span className="mx-1">—</span>
                                                    {t(PROBABILITY_DESCRIPTIONS[formData.gross_probability].descriptionKey, PROBABILITY_DESCRIPTIONS[formData.gross_probability].descriptionKey)}
                                                </p>
                                            )}
                                        </div>
                                        <div>
                                            <label className="flex justify-between text-[10px] font-bold text-slate-500 uppercase mb-2">
                                                <span>{t('risks:fields.impact')}</span>
                                                <span className="text-white">{formData.gross_impact} / 5</span>
                                            </label>
                                            <input
                                                type="range" min="1" max="5" step="1"
                                                value={formData.gross_impact}
                                                onChange={(e) => handleInputChange('gross_impact', parseInt(e.target.value))}
                                                className={`w-full ${getSliderAccent((formData.gross_probability || 1) * (formData.gross_impact || 1))}`}
                                            />
                                            {formData.gross_impact && IMPACT_DESCRIPTIONS[formData.gross_impact] && (
                                                <p className="text-xs text-slate-400 mt-1">
                                                    <span className={`font-semibold ${getScoreTextColor((formData.gross_probability || 1) * (formData.gross_impact || 1))}`}>
                                                        {t(IMPACT_DESCRIPTIONS[formData.gross_impact].labelKey, IMPACT_DESCRIPTIONS[formData.gross_impact].labelKey)}
                                                    </span>
                                                    <span className="mx-1">—</span>
                                                    {t(IMPACT_DESCRIPTIONS[formData.gross_impact].descriptionKey, IMPACT_DESCRIPTIONS[formData.gross_impact].descriptionKey)}.
                                                    <span className="text-slate-500 ml-1">
                                                        {t('form.financial.loss')}: {formatFinancialRange(formData.gross_impact, totalAssets, t('form.financial.no_loss'))}
                                                    </span>
                                                </p>
                                            )}
                                        </div>
                                    </div>

                                    <RiskScoreMatrix
                                        probability={formData.gross_probability || 1}
                                        impact={formData.gross_impact || 1}
                                        type="gross"
                                        size="large"
                                        onSelect={(p, i) => {
                                            handleInputChange('gross_probability', p);
                                            handleInputChange('gross_impact', i);
                                        }}
                                    />
                                </section>

                                <section className="space-y-6">
                                    <h4 className={`text-[10px] font-black uppercase tracking-widest ${getScoreTextColor((formData.net_probability || 1) * (formData.net_impact || 1))}`}>{t('risks:fields.net_score')} ({t('risks:scoring.residual_risk')})</h4>
                                    <div className="space-y-4">
                                        <div>
                                            <label className="flex justify-between text-[10px] font-bold text-slate-500 uppercase mb-2">
                                                <span>{t('risks:fields.probability')}</span>
                                                <span className="text-white">{formData.net_probability} / 5</span>
                                            </label>
                                            <input
                                                type="range" min="1" max="5" step="1"
                                                value={formData.net_probability}
                                                onChange={(e) => handleInputChange('net_probability', parseInt(e.target.value))}
                                                className={`w-full ${getSliderAccent((formData.net_probability || 1) * (formData.net_impact || 1))}`}
                                            />
                                            {formData.net_probability && PROBABILITY_DESCRIPTIONS[formData.net_probability] && (
                                                <p className="text-xs text-slate-400 mt-1">
                                                    <span className={`font-semibold ${getScoreTextColor((formData.net_probability || 1) * (formData.net_impact || 1))}`}>
                                                        {t(PROBABILITY_DESCRIPTIONS[formData.net_probability].labelKey, PROBABILITY_DESCRIPTIONS[formData.net_probability].labelKey)}
                                                    </span>
                                                    <span className="mx-1">—</span>
                                                    {t(PROBABILITY_DESCRIPTIONS[formData.net_probability].descriptionKey, PROBABILITY_DESCRIPTIONS[formData.net_probability].descriptionKey)}
                                                </p>
                                            )}
                                        </div>
                                        <div>
                                            <label className="flex justify-between text-[10px] font-bold text-slate-500 uppercase mb-2">
                                                <span>{t('risks:fields.impact')}</span>
                                                <span className="text-white">{formData.net_impact} / 5</span>
                                            </label>
                                            <input
                                                type="range" min="1" max="5" step="1"
                                                value={formData.net_impact}
                                                onChange={(e) => handleInputChange('net_impact', parseInt(e.target.value))}
                                                className={`w-full ${getSliderAccent((formData.net_probability || 1) * (formData.net_impact || 1))}`}
                                            />
                                            {formData.net_impact && IMPACT_DESCRIPTIONS[formData.net_impact] && (
                                                <p className="text-xs text-slate-400 mt-1">
                                                    <span className={`font-semibold ${getScoreTextColor((formData.net_probability || 1) * (formData.net_impact || 1))}`}>
                                                        {t(IMPACT_DESCRIPTIONS[formData.net_impact].labelKey, IMPACT_DESCRIPTIONS[formData.net_impact].labelKey)}
                                                    </span>
                                                    <span className="mx-1">—</span>
                                                    {t(IMPACT_DESCRIPTIONS[formData.net_impact].descriptionKey, IMPACT_DESCRIPTIONS[formData.net_impact].descriptionKey)}.
                                                    <span className="text-slate-500 ml-1">
                                                        {t('form.financial.loss')}: {formatFinancialRange(formData.net_impact, totalAssets, t('form.financial.no_loss'))}
                                                    </span>
                                                </p>
                                            )}
                                        </div>
                                    </div>

                                    <RiskScoreMatrix
                                        probability={formData.net_probability || 1}
                                        impact={formData.net_impact || 1}
                                        type="net"
                                        size="large"
                                        onSelect={(p, i) => {
                                            handleInputChange('net_probability', p);
                                            handleInputChange('net_impact', i);
                                        }}
                                    />
                                </section>
                            </div>
                        </div>
                    )}

                </div>

                {/* Footer Controls */}
                <div className="mt-12 flex justify-between items-center pt-8 border-t border-white/5">
                    <button
                        type="button"
                        onClick={() => currentStep === 0 ? navigate('/risks') : prevStep()}
                        className="flex items-center gap-2 text-xs font-black text-slate-500 hover:text-white transition-colors uppercase tracking-widest"
                    >
                        {currentStep === 0 ? <X className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}
                        {currentStep === 0 ? t('common:actions.cancel') : t('common:actions.back')}
                    </button>

                    {currentStep < steps.length - 1 ? (
                        <button
                            type="button"
                            onClick={nextStep}
                            className="btn-primary"
                        >
                            {t('common:actions.next')} <ChevronRight className="h-4 w-4" />
                        </button>
                    ) : (
                        <button
                            type="submit"
                            disabled={isSubmitting}
                            className="btn-primary px-8"
                        >
                            {isSubmitting ? t('common:loading.generic') : (isEdit ? t('risks:edit_risk') : t('risks:create_risk'))}
                            <Save className="h-4 w-4" />
                        </button>
                    )}
                </div>
            </div>
        </form >
    );
}
