"""Export reserved native schemas and matching TS; no placeholder API routes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.schemas.local_auth import LOCAL_ENDPOINT_CONTRACTS, LocalAuthChallenge

ROOT = Path(__file__).resolve().parents[2]


def documents() -> dict[Path, str]:
    schemas: dict[str, Any] = {}
    paths: dict[str, Any] = {}
    for endpoint in LOCAL_ENDPOINT_CONTRACTS:
        for model in (endpoint.request, endpoint.response, LocalAuthChallenge):
            schema = model.model_json_schema(ref_template="#/components/schemas/{model}")
            schemas.update(schema.pop("$defs", {}))
            schemas[model.__name__] = schema
        paths["/api/v1" + endpoint.path] = {
            endpoint.method: {
                "x-implementation-issue": endpoint.owner_issue,
                "x-handler-implemented": endpoint.owner_issue in {198, 199, 200},
                "x-authentication": endpoint.authentication,
                "x-profile": "password/none (not released)",
                "x-transaction-owner": "identity/auth service workflow, never endpoint commit",
                "requestBody": {
                    "required": True,
                    "content": {
                        "application/json": {"schema": {"$ref": "#/components/schemas/" + endpoint.request.__name__}}
                    },
                },
                "responses": {
                    str(endpoint.status_code): {
                        "description": "Reserved contract; handler not released",
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/" + endpoint.response.__name__}
                            }
                        },
                    }
                },
            }
        }
        if endpoint.method == "get":
            paths["/api/v1" + endpoint.path]["get"].pop("requestBody")
    spec = {
        "openapi": "3.1.0",
        "info": {
            "title": "RiskHub reserved native identity contract",
            "version": "1.0.0",
            "description": (
                "Native contracts: #198–#200 handlers implemented for component verification; "
                "#201 reserved. Production admission remains closed."
            ),
        },
        "paths": paths,
        "components": {"schemas": schemas},
    }
    ts = "// Generated by backend/scripts/export_local_auth_contract.py. Do not edit.\n"
    ts += "// Native wire types; importing a type does not enable native production authentication.\n\n"
    for name, schema in sorted(schemas.items()):
        ts += f"export type {name} = {typescript_type(schema)};\n\n"
    return {
        ROOT / "docs/security/identity-local-auth.openapi.json": json.dumps(spec, indent=2, sort_keys=True) + "\n",
        ROOT / "frontend/src/types/localAuth.generated.d.ts": ts,
    }


def typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript_type(part) for part in schema["anyOf"])
    kind = schema.get("type")
    if kind == "object":
        if not schema.get("properties"):
            value = schema.get("additionalProperties", {})
            if value is False:
                return "Record<string, never>"
            return f"Record<string, {typescript_type(value) if isinstance(value, dict) else 'unknown'}>"
        required = schema.get("required", [])
        fields = [
            f"  {key}{'' if key in required else '?'}: {typescript_type(value)};"
            for key, value in schema["properties"].items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    if kind == "array":
        return f"Array<{typescript_type(schema.get('items', {}))}>"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(
        kind, "unknown"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in documents().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                parser.exit(1, f"Generated identity contract is stale: {path.relative_to(ROOT)}\n")
        else:
            path.write_text(content)


if __name__ == "__main__":
    main()
