# Security: Only these fields can be modified via approval pending_changes.
# Prevents injection of id, created_at, created_by_id, etc.
EDITABLE_FIELDS = {
    "risk": {
        "risk_id_code",
        "name",
        "process",
        "subprocess",
        "risk_type",
        "category",
        "description",
        "department_id",
        "owner_id",
        "gross_probability",
        "gross_impact",
        "net_probability",
        "net_impact",
        "status",
        "is_priority",
        "acceptance_approver",
        "acceptance_justification",
        "acceptance_date",
    },
    "control": {
        "name",
        "description",
        "data_source",
        "methodology_reference",
        "control_form",
        "process_owner_position",
        "control_owner_id",
        "executor_position",
        "frequency",
        "risk_level",
        "output_description",
        "report_recipient",
        "documentation_location",
        "department_id",
        "status",
    },
    "kri": {
        "metric_name",
        "description",
        "upper_limit",
        "lower_limit",
        "current_value",
        "reporting_owner_id",
        "unit",
        "frequency",
        "linked_vendor_ids",
    },
}
