// Generated by backend/scripts/export_local_auth_contract.py. Do not edit.
// Reserved future wire types; importing a type does not enable native authentication.

export type AcceptedResponse = {
  status?: "accepted";
};

export type AccessScopeEnum = "global" | "department" | "manager";

export type ActionProofResponse = {
  proof: string;
  expires_in?: 300;
};

export type AssistedRecoveryRequest = {
  recent_auth_proof: string;
  incident_reference: string;
  verification_method: string;
  reason: string;
  operation: "factor_recovery" | "credential_and_factor_recovery" | "verified_address_recovery";
};

export type ChallengeRequest = {
  challenge: string;
};

export type CompletedResponse = {
  status?: "completed";
  reauthentication_required?: boolean;
};

export type EmailChangeCompleteRequest = {
  recent_auth_proof: string;
  grant: string;
};

export type EmailChangeRequest = {
  recent_auth_proof: string;
  new_email: string;
};

export type EnrollmentResponse = LocalAuthChallenge | CompletedResponse;

export type EnrollmentStartRequest = {
  grant: string;
  password: string;
};

export type FactorEnrollmentResponse = {
  status?: "enrolled";
  recovery_codes: Array<string>;
};

export type FactorReplacementRequest = {
  recent_auth_proof: string;
};

export type FactorSetupResponse = {
  challenge: string;
  provisioning_uri: string;
  expires_in?: 300;
};

export type FactorVerifyRequest = {
  challenge: string;
  code: string;
  method?: "totp" | "recovery_code";
};

export type InvitationRequest = {
  email: string;
  name: string;
  role_id?: number | null;
  department_id?: number | null;
  manager_id?: number | null;
};

export type InvitationResponse = {
  user_id: number;
  enrollment_state?: "invited";
  delivery_status: "pending" | "sent" | "failed";
};

export type LocalAuthChallenge = {
  status: "mfa_required" | "enrollment_required";
  challenge: string;
  expires_in?: 300;
};

export type MeCapabilities = {
  can_view_user_directory?: boolean;
  can_view_access_users?: boolean;
  can_view_department_access_users?: boolean;
  can_view_users_route?: boolean;
  can_view_approvals?: boolean;
  can_manage_access?: boolean;
  can_view_department_access?: boolean;
  can_view_admin_console?: boolean;
  can_view_riskhub?: boolean;
  can_view_governance?: boolean;
  can_view_activity_log?: boolean;
  can_view_committee?: boolean;
  can_view_users_page?: boolean;
  is_second_line?: boolean;
  can_read_risks?: boolean;
  can_read_controls?: boolean;
  can_read_vendors?: boolean;
  can_read_departments?: boolean;
  resource_permissions?: Record<string, boolean>;
};

export type PasswordChangeRequest = {
  recent_auth_proof: string;
  password: string;
};

export type ReasonRequest = {
  reason: string;
};

export type RecentAuthenticationRequest = {
  password: string;
  factor?: string | null;
  method?: "totp" | "recovery_code";
  target_user_id: number;
  operation: "password_change" | "email_change" | "factor_enroll" | "factor_replace" | "recovery_codes" | "assisted_recovery";
  intended_password?: string | null;
  intended_email?: string | null;
  intended_recovery_operation?: "factor_recovery" | "credential_and_factor_recovery" | "verified_address_recovery" | null;
};

export type RecoveryStartRequest = {
  grant: string;
  current_password?: string | null;
  new_password?: string | null;
};

export type ResetCompleteRequest = {
  grant: string;
  password: string;
};

export type ResetRequest = {
  email: string;
};

export type TokenResponse = {
  access_token: string;
  token_type?: string;
  user: UserBrief;
  post_login_redirect_to?: string | null;
};

export type UserBrief = {
  id: number;
  email: string;
  name: string;
  role: string;
  role_display_name: string;
  permissions: Array<string>;
  effective_permissions: Array<string>;
  access_scope: AccessScopeEnum;
  scope_label: string;
  entra_business_role?: string | null;
  department_id?: number | null;
  department_name?: string | null;
  me_capabilities?: MeCapabilities | null;
};

