// Risk types matching backend schemas from OS 18 Řízení rizik
// Now supports arbitrary types configured in Risk Hub (not just S/O)

import type { ControlMonitoringFields } from './control';
import type { CollectionListResponse } from './collection';
import type { KeyRiskIndicator } from './kri';
import type { LinkedVendorSummary } from './vendorLink';

export type RiskType = string;
export const RiskTypeCodes = {
    STRATEGIC: 'strategic',
    OPERATIONAL: 'operational',
} as const;

export type RiskStatus = 'active' | 'emerging' | 'archived';
export const RiskStatus = {
    ACTIVE: 'active' as RiskStatus,
    EMERGING: 'emerging' as RiskStatus,
    ARCHIVED: 'archived' as RiskStatus,
};

export type ControlEffectiveness = 'high' | 'medium' | 'low';
export const ControlEffectiveness = {
    HIGH: 'high' as ControlEffectiveness,
    MEDIUM: 'medium' as ControlEffectiveness,
    LOW: 'low' as ControlEffectiveness,
};

export interface Risk {
    id: number;
    risk_id_code: string;
    name: string;
    process: string;
    subprocess?: string | null;
    risk_type: RiskType;
    category?: string | null;
    description: string;
    department_id?: number | null;
    owner_id?: number | null;

    // Gross risk (before controls)
    gross_probability: number;
    gross_impact: number;
    gross_score: number;

    // Net risk (after controls)
    net_probability: number;
    net_impact: number;
    net_score: number;

    status: RiskStatus;
    is_priority: boolean;

    // KRI thresholds (legacy) - string for form input
    kri_indicator?: string;
    kri_threshold_green?: string;
    kri_threshold_yellow?: string;
    kri_threshold_red?: string;

    created_at: string;
    updated_at: string;

    // Relationships
    kris?: KeyRiskIndicator[];
    owner?: {
        id: number;
        name: string;
        email: string;
    } | null;
    department?: {
        id: number;
        name: string;
        code: string;
    } | null;
}

export interface RiskSummary {
    id: number;
    risk_id_code: string;
    name: string;
    process: string;
    risk_type: RiskType;
    category?: string | null;
    description: string;
    gross_score: number;
    gross_probability: number;
    gross_impact: number;
    net_score: number;
    status: RiskStatus;
    is_priority: boolean;
    department_id?: number | null;
    department_name?: string | null;
    owner_id?: number;
    kri_count?: number;
    has_breach?: boolean;
    control_count?: number;
    linked_vendors?: LinkedVendorSummary[];
}

export interface RiskCreate {
    risk_id_code?: string;  // Auto-generated by backend if not provided
    name: string;
    process: string;
    subprocess?: string;
    risk_type: RiskType;
    category?: string;
    description: string;
    department_id?: number;
    owner_id?: number;
    gross_probability: number;
    gross_impact: number;
    net_probability: number;
    net_impact: number;
    status?: RiskStatus;
    is_priority?: boolean;
}

export type RiskUpdate = Partial<RiskCreate>;

export interface RiskControlLink {
    id: number;
    control_id: number;
    risk_id: number;
    effectiveness: ControlEffectiveness;
    notes?: string | null;
    created_at: string;
    control?: ControlMonitoringFields & {
        id: number;
        name: string;
        frequency: string;
        risk_level: number;
        status: string;
    };
    risk?: {
        id: number;
        risk_id_code: string;
        process: string;
        gross_score: number;
        net_score: number;
    };
}

export type RiskListResponse = CollectionListResponse<RiskSummary>;
