import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
    Save,
    X,
    ChevronRight,
    ChevronLeft,
    AlertCircle,
    Info,
    User,
    Activity,
    Clock,
    CheckCircle
} from 'lucide-react';
import { useTranslation } from '@/i18n/hooks';
import { StepIndicator } from '@/components/ui/StepIndicator';
import { riskApi } from '@/services/riskApi';
import { ApiClientError } from '@/services/apiClient';
import { lookupApi } from '@/services/lookupApi';
import type { UserLookupItem } from '@/services/lookupApi';
import type { Risk, RiskCreate, RiskUpdate } from '@/types/risk';
import { RiskStatus } from '@/types/risk';
import { useRiskTypes, useTotalAssetsValue, useRiskThresholds } from '@/hooks/useRiskHubConfig';
import { parseUpdateResult } from '@/lib/approvalUi';
import { RiskFormIdentityStep } from './RiskFormIdentityStep';
import { RiskFormOwnershipStep } from './RiskFormOwnershipStep';
import { RiskFormScoringStep } from './RiskFormScoringStep';

interface RiskFormProps {
    initialData?: Risk;
    isEdit?: boolean;
}

export function RiskForm({ initialData, isEdit = false }: RiskFormProps) {
    const navigate = useNavigate();
    const { t } = useTranslation(['risks', 'common', 'errorKeys', 'approvals']);
    const steps = [
        { id: 'identity', title: t('risks:form.steps.identity'), icon: Info },
        { id: 'ownership', title: t('risks:form.steps.ownership'), icon: User },
        { id: 'scoring', title: t('risks:form.steps.scoring'), icon: Activity },
    ];
    const [currentStep, setCurrentStep] = useState(0);
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Approval-queued state for edit flows (HTTP 202)
    const [approvalQueued, setApprovalQueued] = useState<{ id: number; message: string } | null>(null);

    // Fetch risk types from Risk Hub
    const { riskTypes, isLoading: riskTypesLoading } = useRiskTypes();

    // Fetch total assets for financial loss calculations
    const { totalAssets } = useTotalAssetsValue();

    // Get thresholds for score-based colors
    const { thresholds } = useRiskThresholds();

    // Helper to get text color class based on score
    const getScoreTextColor = (score: number) => {
        if (score >= thresholds.critical) return 'text-rose-400';
        if (score >= thresholds.high) return 'text-orange-400';
        if (score >= thresholds.medium) return 'text-amber-400';
        return 'text-emerald-400';
    };

    // Helper to get slider accent color based on score
    const getSliderAccent = (score: number) => {
        if (score >= thresholds.critical) return 'accent-rose-500';
        if (score >= thresholds.high) return 'accent-orange-500';
        if (score >= thresholds.medium) return 'accent-amber-500';
        return 'accent-emerald-500';
    };

    // Validation errors (inline)
    const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

    interface DepartmentLookup {
        id: number;
        name: string;
        code?: string;
    }

    // Lookups
    const [users, setUsers] = useState<UserLookupItem[]>([]);
    const [departments, setDepartments] = useState<DepartmentLookup[]>([]);
    const [existingProcesses, setExistingProcesses] = useState<string[]>([]);
    const [existingCategories, setExistingCategories] = useState<string[]>([]);
    const [subprocessesByProcess, setSubprocessesByProcess] = useState<Record<string, string[]>>({});
    const [showProcessDropdown, setShowProcessDropdown] = useState(false);
    const [showSubprocessDropdown, setShowSubprocessDropdown] = useState(false);
    const [showCategoryDropdown, setShowCategoryDropdown] = useState(false);

    // Owner search/filter
    const [ownerSearch, setOwnerSearch] = useState('');
    const [roleFilter, setRoleFilter] = useState<string>('');

    const [formData, setFormData] = useState<Partial<Risk>>(() => ({
        // risk_id_code is auto-generated by backend
        name: '',
        process: '',
        subprocess: '',
        risk_type: initialData?.risk_type || 'operational',
        category: '',
        description: '',
        status: RiskStatus.ACTIVE,
        is_priority: false,
        gross_probability: 3,
        gross_impact: 3,
        net_probability: 2,
        net_impact: 2,
        kri_indicator: '',
        kri_threshold_green: '',
        kri_threshold_yellow: '',
        kri_threshold_red: '',
        ...initialData
    }));

    useEffect(() => {
        const loadLookups = async () => {
            try {
                const [userData, deptData, risksData] = await Promise.all([
                    lookupApi.getUsers(),
                    lookupApi.getDepartments(),
                    riskApi.getRisks({ skip: 0, limit: 100 })
                ]);
                setUsers(userData);
                setDepartments(deptData);

                // Extract unique process names
                type RiskItem = { process?: string; subprocess?: string; category?: string };
                const processes = [...new Set(risksData.items.map((r: RiskItem) => r.process).filter(Boolean))];
                setExistingProcesses(processes as string[]);

                // Extract unique categories
                const categories = [...new Set(risksData.items.map((r: RiskItem) => r.category).filter(Boolean))];
                setExistingCategories(categories as string[]);

                // Build subprocess map by process
                const subprocMap: Record<string, string[]> = {};
                risksData.items.forEach((r: RiskItem) => {
                    if (r.process && r.subprocess) {
                        if (!subprocMap[r.process]) subprocMap[r.process] = [];
                        if (!subprocMap[r.process].includes(r.subprocess)) {
                            subprocMap[r.process].push(r.subprocess);
                        }
                    }
                });
                setSubprocessesByProcess(subprocMap);
            } catch (err) {
                console.error('Failed to load lookups:', err);
            }
        };
        loadLookups();
    }, []);

    const handleInputChange = (field: keyof Risk, value: unknown) => {
        setFormData(prev => {
            const newData = { ...prev, [field]: value };

            // Auto-fill department when owner is selected
            if (field === 'owner_id' && value) {
                const selectedUser = users.find(u => u.id === value);
                if (selectedUser?.department_id) {
                    newData.department_id = selectedUser.department_id;
                }
            }

            return newData;
        });

        // Clear errors outside of setFormData to avoid stale closure
        setFieldErrors(prev => {
            const newErrors = { ...prev };
            if (prev[field]) {
                newErrors[field] = '';
            }
            // Also clear department error when auto-filled
            if (field === 'owner_id' && prev.department_id) {
                newErrors.department_id = '';
            }
            return newErrors;
        });
    };

    // Validate Step 1: Identity
    const validateStep1 = (): boolean => {
        const errors: Record<string, string> = {};

        if (!formData.name?.trim()) {
            errors.name = 'Risk Name is required';
        }
        if (!formData.process?.trim()) {
            errors.process = 'Main Process is required';
        }
        if (!formData.category?.trim()) {
            errors.category = 'Category is required';
        }
        if (!formData.description?.trim()) {
            errors.description = 'Risk Description is required';
        }

        setFieldErrors(errors);
        return Object.keys(errors).length === 0;
    };

    // Validate Step 2: Details & Owner
    const validateStep2 = (): boolean => {
        const errors: Record<string, string> = {};

        if (!formData.department_id) {
            errors.department_id = 'Department is required';
        }
        if (!formData.owner_id) {
            errors.owner_id = 'Risk Owner is required';
        }

        setFieldErrors(errors);
        return Object.keys(errors).length === 0;
    };

    // Filtered users based on search, role, AND department
    const filteredUsers = users.filter(user => {
        const matchesSearch = !ownerSearch ||
            user.name?.toLowerCase().includes(ownerSearch.toLowerCase()) ||
            user.email?.toLowerCase().includes(ownerSearch.toLowerCase());
        const matchesRole = !roleFilter || user.role_name === roleFilter;
        // If department is selected, filter to that department's users
        const matchesDepartment = !formData.department_id || user.department_id === formData.department_id;
        return matchesSearch && matchesRole && matchesDepartment;
    });

    // Get unique roles for filter - role is an object with name property
    const uniqueRoles: string[] = [...new Set(users.map(u => u.role_name).filter((r): r is string => !!r))];

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Validate all steps before submission
        if (!validateStep1()) {
            setCurrentStep(0);
            return;
        }
        if (!validateStep2()) {
            setCurrentStep(1);
            return;
        }

        try {
            setIsSubmitting(true);
            setError(null);
            setApprovalQueued(null);

            if (isEdit && initialData) {
                const result = await riskApi.updateRisk(initialData.id, formData as RiskUpdate);
                // Use standardized helper to check for 202 approval-queued response
                const parsed = parseUpdateResult(result);
                if (parsed.kind === 'approval') {
                    setApprovalQueued({
                        id: parsed.approvalId,
                        message: parsed.message,
                    });
                    setIsSubmitting(false);
                    return; // Stay on form, don't navigate
                }
            } else {
                const newRisk = await riskApi.createRisk(formData as RiskCreate);
                navigate(`/risks/${newRisk.id}`);
                return;
            }

            navigate(`/risks/${initialData?.id}`);
        } catch (err: unknown) {
            console.error('Error saving risk:', err);
            if (err instanceof ApiClientError) {
                setError(err.messageKey);
            } else {
                setError('errorKeys.save_risk_failed');
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    const nextStep = (e?: React.MouseEvent) => {
        if (e) {
            e.preventDefault();
            e.stopPropagation();
        }
        // Validate current step before proceeding
        if (currentStep === 0 && !validateStep1()) return;
        if (currentStep === 1 && !validateStep2()) return;
        setCurrentStep(prev => Math.min(prev + 1, steps.length - 1));
    };
    const prevStep = () => setCurrentStep(prev => Math.max(prev - 1, 0));

    return (
        <form onSubmit={handleSubmit} className="space-y-8 max-w-4xl mx-auto">
            {/* Multi-step indicator */}
            <StepIndicator
                steps={steps}
                currentStep={currentStep}
                isStepClickable={(idx) => isEdit || idx < currentStep}
                onStepClick={(idx) => setCurrentStep(idx)}
            />

            <div className="glass-card min-h-[480px] flex flex-col">
                {/* Approval-queued banner */}
                {approvalQueued && (
                    <div className="mb-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-start gap-3 animate-in fade-in slide-in-from-top-2">
                        <Clock className="h-5 w-5 text-amber-400 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                            <p className="text-amber-200 text-sm font-medium">
                                {t('approval_submitted', { ns: 'errorKeys' })} (ID: {approvalQueued.id})
                            </p>
                            <p className="text-amber-400/80 text-xs mt-1">
                                {approvalQueued.message.startsWith('errorKeys.') ? t(approvalQueued.message, { ns: 'errorKeys' }) : approvalQueued.message}
                            </p>
                            <div className="mt-3 flex gap-3">
                                <Link
                                    to="/approvals"
                                    className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-300 hover:text-amber-100 transition-colors"
                                >
                                    <CheckCircle className="h-3.5 w-3.5" />
                                    {t('common:actions.view')} {t('approvals:title', { ns: 'approvals', defaultValue: 'Approvals' })}
                                </Link>
                                <button
                                    type="button"
                                    onClick={() => setApprovalQueued(null)}
                                    className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
                                >
                                    {t('common:actions.close')}
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {error && (
                    <div className="mb-6 p-4 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-center gap-3 text-rose-400 text-sm font-medium">
                        <AlertCircle className="h-5 w-5" />
                        {error.startsWith('errorKeys.') ? t(error, { ns: 'errorKeys' }) : error}
                    </div>
                )}

                <div className="flex-1 space-y-6">
                    {currentStep === 0 && (
                        <RiskFormIdentityStep
                            t={t}
                            formData={formData}
                            fieldErrors={fieldErrors}
                            riskTypes={riskTypes}
                            riskTypesLoading={riskTypesLoading}
                            existingProcesses={existingProcesses}
                            existingCategories={existingCategories}
                            subprocessesByProcess={subprocessesByProcess}
                            showProcessDropdown={showProcessDropdown}
                            showSubprocessDropdown={showSubprocessDropdown}
                            showCategoryDropdown={showCategoryDropdown}
                            setShowProcessDropdown={setShowProcessDropdown}
                            setShowSubprocessDropdown={setShowSubprocessDropdown}
                            setShowCategoryDropdown={setShowCategoryDropdown}
                            handleInputChange={handleInputChange}
                        />
                    )}

                    {currentStep === 1 && (
                        <RiskFormOwnershipStep
                            t={t}
                            formData={formData}
                            fieldErrors={fieldErrors}
                            departments={departments}
                            users={users}
                            filteredUsers={filteredUsers}
                            uniqueRoles={uniqueRoles}
                            ownerSearch={ownerSearch}
                            roleFilter={roleFilter}
                            setOwnerSearch={setOwnerSearch}
                            setRoleFilter={setRoleFilter}
                            handleInputChange={handleInputChange}
                        />
                    )}

                    {currentStep === 2 && (
                        <RiskFormScoringStep
                            t={t}
                            formData={formData}
                            totalAssets={totalAssets}
                            handleInputChange={handleInputChange}
                            getScoreTextColor={getScoreTextColor}
                            getSliderAccent={getSliderAccent}
                        />
                    )}

                </div>

                {/* Footer Controls */}
                <div className="mt-12 flex justify-between items-center pt-8 border-t border-white/5">
                    <button
                        type="button"
                        onClick={() => currentStep === 0 ? navigate('/risks') : prevStep()}
                        className="flex items-center gap-2 text-xs font-black text-slate-500 hover:text-white transition-colors uppercase tracking-widest"
                    >
                        {currentStep === 0 ? <X className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}
                        {currentStep === 0 ? t('common:actions.cancel') : t('common:actions.back')}
                    </button>

                    {currentStep < steps.length - 1 ? (
                        <button
                            type="button"
                            onClick={nextStep}
                            className="btn-primary"
                        >
                            {t('common:actions.next')} <ChevronRight className="h-4 w-4" />
                        </button>
                    ) : (
                        <button
                            type="submit"
                            disabled={isSubmitting}
                            className="btn-primary px-8"
                        >
                            {isSubmitting ? t('common:loading.generic') : (isEdit ? t('risks:edit_risk') : t('risks:create_risk'))}
                            <Save className="h-4 w-4" />
                        </button>
                    )}
                </div>
            </div>
        </form >
    );
}
