"""Static seed payloads used by backend/app/db/seed.py."""

# Sample departments
DEPARTMENTS = [
    {"name": "Operations", "code": "OPS", "description": "Operations department"},
    {"name": "Finance", "code": "FIN", "description": "Finance and accounting"},
    {"name": "IT", "code": "IT", "description": "Information technology"},
    {"name": "Risk Management", "code": "RISK", "description": "Risk management function"},
    {"name": "Compliance", "code": "COMP", "description": "Compliance function"},
]

# Demo users - structured for testing different permission levels
# ID 1-3: Privileged accounts (full access)
# ID 4-6: Department heads (department-scoped write access)
# ID 7-9: Employees (limited access under department heads)
TEST_USERS = [
    # Privileged accounts
    {
        "email": "admin@riskhub.local",
        "name": "System Admin",
        "role": "admin",
        "department": None,
        "access_scope": "global",
    },
    {
        "email": "cro@riskhub.local",
        "name": "Anna Kowalski",
        "role": "cro",
        "department": "RISK",
        "access_scope": "global",
    },
    {
        "email": "risk.manager@riskhub.local",
        "name": "Petra Svobodová",
        "role": "risk_manager",
        "department": "RISK",
        "access_scope": "global",
    },
    # Department heads
    {
        "email": "ops.head@riskhub.local",
        "name": "Eva Králová",
        "role": "department_head",
        "department": "OPS",
        "access_scope": "department",
    },
    {
        "email": "fin.head@riskhub.local",
        "name": "Martin Procházka",
        "role": "department_head",
        "department": "FIN",
        "access_scope": "department",
    },
    {
        "email": "it.head@riskhub.local",
        "name": "Tomáš Novotný",
        "role": "department_head",
        "department": "IT",
        "access_scope": "department",
    },
    # Employees (control owners under department heads)
    {
        "email": "ops.analyst@riskhub.local",
        "name": "Jana Horáková",
        "role": "employee",
        "department": "OPS",
        "access_scope": "department",
    },
    {
        "email": "fin.analyst@riskhub.local",
        "name": "Lukáš Dvořák",
        "role": "employee",
        "department": "FIN",
        "access_scope": "department",
    },
    {
        "email": "it.analyst@riskhub.local",
        "name": "Barbora Němcová",
        "role": "employee",
        "department": "IT",
        "access_scope": "department",
    },
]

# Sample controls based on DEFINICIA KONTROL
SAMPLE_CONTROLS = [
    {
        "name": "Daily Cash Reconciliation",
        "description": "Verify daily cash balances against bank statements",
        "data_source": "Bank statements, ERP system",
        "methodology_reference": "OS-FIN-001",
        "control_form": "manual",
        "process_owner_position": "Finance Director",
        "executor_position": "Financial Analyst",
        "frequency": "daily",
        "risk_level": 4,
        "output_description": "Reconciliation report with variances",
        "report_recipient": "CFO, Finance Director",
        "documentation_location": "SharePoint/Finance/Reconciliation",
        "department": "FIN",
        "status": "active",
    },
    {
        "name": "IT Access Review",
        "description": "Quarterly review of user access rights to critical systems",
        "data_source": "Active Directory, Application access logs",
        "methodology_reference": "OS-IT-015",
        "control_form": "manual",
        "process_owner_position": "IT Security Manager",
        "executor_position": "IT Security Analyst",
        "frequency": "quarterly",
        "risk_level": 5,
        "output_description": "Access review report with remediation actions",
        "report_recipient": "CISO, IT Director",
        "documentation_location": "SharePoint/IT/Security/AccessReviews",
        "department": "IT",
        "status": "active",
    },
    {
        "name": "Insurance Policy Underwriting Check",
        "description": "Automated validation of policy underwriting parameters",
        "data_source": "Underwriting system",
        "methodology_reference": "OS-OPS-022",
        "control_form": "automatic",
        "process_owner_position": "Chief Underwriter",
        "executor_position": "System",
        "frequency": "daily",
        "risk_level": 5,
        "output_description": "Exception report for out-of-policy underwriting",
        "report_recipient": "Chief Underwriter, Risk Manager",
        "documentation_location": "UW System logs",
        "department": "OPS",
        "status": "active",
    },
    {
        "name": "Regulatory Compliance Monitoring",
        "description": "Monthly review of regulatory changes and compliance status",
        "data_source": "Regulatory bulletins, Internal compliance database",
        "methodology_reference": "OS-COMP-003",
        "control_form": "manual",
        "process_owner_position": "Compliance Officer",
        "executor_position": "Compliance Analyst",
        "frequency": "monthly",
        "risk_level": 4,
        "output_description": "Compliance status report with action items",
        "report_recipient": "CRO, Board",
        "documentation_location": "SharePoint/Compliance/Monthly",
        "department": "COMP",
        "status": "active",
    },
    {
        "name": "Claims Reserve Validation",
        "description": "Actuarial review of claims reserves accuracy",
        "data_source": "Claims system, Actuarial models",
        "methodology_reference": "OS-FIN-045",
        "control_form": "manual",
        "process_owner_position": "Chief Actuary",
        "executor_position": "Senior Actuary",
        "frequency": "quarterly",
        "risk_level": 5,
        "output_description": "Reserve adequacy report",
        "report_recipient": "CFO, Audit Committee",
        "documentation_location": "SharePoint/Actuarial/Reserves",
        "department": "FIN",
        "status": "active",
    },
    {
        "name": "Vendor Invoice Approval",
        "description": "Three-way matching of PO, receipt, and invoice before payment",
        "data_source": "ERP system, Purchase orders",
        "methodology_reference": "OS-FIN-012",
        "control_form": "automatic",
        "process_owner_position": "Finance Manager",
        "executor_position": "System",
        "frequency": "daily",
        "risk_level": 3,
        "output_description": "Approved/rejected invoice list",
        "report_recipient": "Finance Manager",
        "documentation_location": "ERP audit trail",
        "department": "FIN",
        "status": "active",
    },
]

# Sample risks based on OS 18 Registr rizik
SAMPLE_RISKS = [
    {
        "risk_id_code": "FIN-R01",
        "process": "Finance",
        "subprocess": "Cash Management",
        "risk_type": "operational",
        "category": "Operational Risk",
        "description": "Cash flow mismanagement leading to liquidity issues",
        "gross_probability": 3,
        "gross_impact": 4,
        "net_probability": 2,
        "net_impact": 3,
        "department": "FIN",
        "is_priority": True,
        "kri_indicator": "Days Cash on Hand",
        "kri_threshold_green": "> 60 days",
        "kri_threshold_yellow": "30-60 days",
        "kri_threshold_red": "< 30 days",
    },
    {
        "risk_id_code": "IT-R01",
        "process": "IT",
        "subprocess": "Access Control",
        "risk_type": "operational",
        "category": "Cyber Risk",
        "description": "Unauthorized access to critical systems",
        "gross_probability": 4,
        "gross_impact": 5,
        "net_probability": 2,
        "net_impact": 4,
        "department": "IT",
        "is_priority": True,
        "kri_indicator": "Failed login attempts",
        "kri_threshold_green": "< 10 per day",
        "kri_threshold_yellow": "10-50 per day",
        "kri_threshold_red": "> 50 per day",
    },
    {
        "risk_id_code": "UW-R01",
        "process": "Underwriting",
        "subprocess": "Policy Issuance",
        "risk_type": "strategic",
        "category": "Underwriting Risk",
        "description": "Underpricing of policies leading to loss ratio deterioration",
        "gross_probability": 3,
        "gross_impact": 5,
        "net_probability": 2,
        "net_impact": 4,
        "department": "OPS",
        "is_priority": True,
        "kri_indicator": "Loss Ratio",
        "kri_threshold_green": "< 65%",
        "kri_threshold_yellow": "65-75%",
        "kri_threshold_red": "> 75%",
    },
    {
        "risk_id_code": "COMP-R01",
        "process": "Compliance",
        "subprocess": "Regulatory",
        "risk_type": "strategic",
        "category": "Regulatory Risk",
        "description": "Non-compliance with regulatory requirements",
        "gross_probability": 2,
        "gross_impact": 5,
        "net_probability": 1,
        "net_impact": 4,
        "department": "COMP",
        "is_priority": False,
        "kri_indicator": "Open compliance gaps",
        "kri_threshold_green": "0",
        "kri_threshold_yellow": "1-3",
        "kri_threshold_red": "> 3",
    },
    {
        "risk_id_code": "FIN-R02",
        "process": "Finance",
        "subprocess": "Reserving",
        "risk_type": "operational",
        "category": "Reserving Risk",
        "description": "Inadequate claims reserves leading to financial misstatement",
        "gross_probability": 3,
        "gross_impact": 5,
        "net_probability": 2,
        "net_impact": 3,
        "department": "FIN",
        "is_priority": True,
        "kri_indicator": "Reserve Adequacy Ratio",
        "kri_threshold_green": "95-105%",
        "kri_threshold_yellow": "90-95% or 105-110%",
        "kri_threshold_red": "< 90% or > 110%",
    },
]

# Control-Risk links (control index, risk index, effectiveness)
CONTROL_RISK_LINKS = [
    (0, 0, "high", "Daily reconciliation directly monitors cash"),
    (1, 1, "high", "Access review prevents unauthorized access"),
    (2, 2, "high", "Automated checks prevent underpricing"),
    (3, 3, "high", "Regular monitoring ensures compliance"),
    (4, 4, "high", "Reserve validation ensures adequacy"),
    (5, 0, "medium", "Invoice approval affects cash outflow"),
]


