#!/usr/bin/env python3
"""Regenerate the exact backend development and audit dependency lock."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_ROOT = REPO_ROOT / "backend"
TOOLCHAIN = REPO_ROOT / ".tool-versions"
INPUT = BACKEND_ROOT / "requirements-dev.in"
DEV_LOCK = BACKEND_ROOT / "requirements-dev-constraints.txt"
AUDIT_LOCK = BACKEND_ROOT / "requirements-prod-readiness-audit-constraints.txt"
ENTRYPOINT = BACKEND_ROOT / "requirements-dev.txt"

PYTHON_MAJOR_MINOR = (3, 13)
PIP_VERSION = "26.0"
AUDIT_REQUIREMENT = "pip-audit==2.10.0"
PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([^\s;]+)$")
LOCK_HEADER = (
    "# Exact Python 3.13 resolver output for backend development/test and the\n"
    "# isolated production-readiness audit environment.\n"
    "# Generated by: python3 scripts/tools/refresh_python_dependency_lock.py\n"
    "# Do not edit manually.\n"
)


def _canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _toolchain_versions() -> dict[str, str]:
    versions: dict[str, str] = {}
    for raw_line in TOOLCHAIN.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        name, version = line.split(maxsplit=1)
        versions[name] = version
    return versions


def _run(command: list[str], *, cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd, check=True)


def _normalize_freeze(raw_output: str) -> str:
    pinned: dict[str, str] = {}
    for raw_line in raw_output.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = PIN_RE.fullmatch(line)
        if match is None:
            raise ValueError(f"resolver emitted a non-exact or non-index requirement: {line}")
        canonical_name = _canonical_name(match.group(1))
        if canonical_name in pinned:
            raise ValueError(f"resolver emitted duplicate package: {canonical_name}")
        pinned[canonical_name] = line
    ordered = [pinned[name] for name in sorted(pinned)]
    return LOCK_HEADER + "\n".join(ordered) + "\n"


def _entrypoint_content(lock_content: str) -> str:
    digest = hashlib.sha256(lock_content.encode("utf-8")).hexdigest()
    return (
        "# Canonical backend development/test install entrypoint.\n"
        "# Human-edited intent lives in requirements-dev.in; exact resolution is enforced\n"
        "# by requirements-dev-constraints.txt for both local setup and CI.\n"
        f"# lock-sha256: {digest}\n"
        "-c requirements-dev-constraints.txt\n"
        "-r requirements-dev.in\n"
    )


def generate_lock() -> str:
    versions = _toolchain_versions()
    expected_python = versions.get("python")
    if expected_python != "3.13":
        raise RuntimeError(".tool-versions must declare python 3.13")
    if sys.version_info[:2] != PYTHON_MAJOR_MINOR:
        raise RuntimeError(
            "lock regeneration requires Python 3.13; "
            f"got {sys.version_info.major}.{sys.version_info.minor}"
        )

    with tempfile.TemporaryDirectory(prefix="riskhub-python-lock-") as temp_dir:
        venv_dir = Path(temp_dir) / "venv"
        _run([sys.executable, "-m", "venv", str(venv_dir)])
        venv_python = venv_dir / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
        _run(
            [
                str(venv_python),
                "-m",
                "pip",
                "install",
                "--upgrade",
                f"pip=={PIP_VERSION}",
            ]
        )
        _run(
            [
                str(venv_python),
                "-m",
                "pip",
                "install",
                "-r",
                str(INPUT),
                AUDIT_REQUIREMENT,
            ],
            cwd=BACKEND_ROOT,
        )
        freeze = subprocess.run(
            [str(venv_python), "-m", "pip", "freeze", "--all"],
            cwd=BACKEND_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    return _normalize_freeze(freeze)


def refresh(*, check: bool) -> int:
    lock_content = generate_lock()
    expected_files = {
        DEV_LOCK: lock_content,
        AUDIT_LOCK: lock_content,
        ENTRYPOINT: _entrypoint_content(lock_content),
    }

    changed: list[Path] = []
    for path, expected in expected_files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != expected:
            changed.append(path)
            if not check:
                path.write_text(expected, encoding="utf-8")

    if check and changed:
        for path in changed:
            print(f"stale dependency lock: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1

    if changed:
        print("Updated backend Python dependency lock:")
        for path in changed:
            print(f"- {path.relative_to(REPO_ROOT)}")
    else:
        print("Backend Python dependency lock is current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate RiskHub's exact Python 3.13 development/audit lock."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="resolve in a temporary environment and fail instead of writing stale files",
    )
    args = parser.parse_args()
    return refresh(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
