"""add_department_management_fields

Revision ID: 0f9fcd4d46c5
Revises: 79d8bd62f3f4
Create Date: 2026-01-03 12:36:47.723770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9fcd4d46c5'
down_revision: Union[str, Sequence[str], None] = '79d8bd62f3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('departments', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'manager_id')
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
