"""add_approval_requests

Revision ID: 1b8059476a03
Revises: f1a2b3c4d5e6
Create Date: 2025-12-27 22:44:15.954152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8059476a03'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.Enum('RISK', 'CONTROL', 'KRI', name='approval_resource_type', create_constraint=True), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approval_status', create_constraint=True), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requested_by', 'approval_requests', ['requested_by_id'], unique=False)
    op.create_index('ix_approval_resource', 'approval_requests', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_approval_status', 'approval_requests', ['status'], unique=False)
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.drop_index('ix_approval_status', table_name='approval_requests')
    op.drop_index('ix_approval_resource', table_name='approval_requests')
    op.drop_index('ix_approval_requested_by', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
