"""add orphaned_items table

Revision ID: 514f30f4b0c9
Revises: 0dde69b2986b
Create Date: 2025-12-29 11:18:15.222026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514f30f4b0c9'
down_revision: Union[str, Sequence[str], None] = '0dde69b2986b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orphaned_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('previous_owner_id', sa.Integer(), nullable=False),
    sa.Column('orphaned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('new_owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['new_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orphaned_items_item_id'), 'orphaned_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_orphaned_items_item_type'), 'orphaned_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_orphaned_items_previous_owner_id'), 'orphaned_items', ['previous_owner_id'], unique=False)
    op.create_index(op.f('ix_orphaned_items_status'), 'orphaned_items', ['status'], unique=False)
    _drop_directory_users_external_id_unique_constraint()
    op.drop_index(op.f('ix_directory_users_external_id'), table_name='directory_users')
    op.create_index(op.f('ix_directory_users_external_id'), 'directory_users', ['external_id'], unique=True)
    # ### end Alembic commands ###


def _drop_directory_users_external_id_unique_constraint() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for constraint in inspector.get_unique_constraints('directory_users'):
        if constraint.get('column_names') == ['external_id'] and constraint.get('name'):
            op.drop_constraint(constraint['name'], 'directory_users', type_='unique')
            return


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directory_users_external_id'), table_name='directory_users')
    op.create_index(op.f('ix_directory_users_external_id'), 'directory_users', ['external_id'], unique=False)
    op.create_unique_constraint(op.f('directory_users_external_id_key'), 'directory_users', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orphaned_items_status'), table_name='orphaned_items')
    op.drop_index(op.f('ix_orphaned_items_previous_owner_id'), table_name='orphaned_items')
    op.drop_index(op.f('ix_orphaned_items_item_type'), table_name='orphaned_items')
    op.drop_index(op.f('ix_orphaned_items_item_id'), table_name='orphaned_items')
    op.drop_table('orphaned_items')
    # ### end Alembic commands ###
