"""add_tiered_approval_fields

Revision ID: 597c3ba51f80
Revises: e3f4a5b6c7d8
Create Date: 2026-01-01 16:14:30.728961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597c3ba51f80'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('primary_approver_id', sa.Integer(), nullable=True))
    op.add_column('approval_requests', sa.Column('primary_approved_at', sa.DateTime(), nullable=True))
    op.add_column('approval_requests', sa.Column('requires_privileged_approval', sa.Boolean(), nullable=False))
    op.add_column('approval_requests', sa.Column('privileged_approver_id', sa.Integer(), nullable=True))
    op.add_column('approval_requests', sa.Column('privileged_approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'approval_requests', 'users', ['primary_approver_id'], ['id'])
    op.create_foreign_key(None, 'approval_requests', 'users', ['privileged_approver_id'], ['id'])
    op.alter_column('departments', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='System departments cannot be deleted',
               existing_server_default=sa.text('false'))
    op.alter_column('directory_sync_logs', 'errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('directory_users', 'source_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('directory_users', 'source_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('directory_sync_logs', 'errors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('departments', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='System departments cannot be deleted',
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.drop_column('approval_requests', 'privileged_approved_at')
    op.drop_column('approval_requests', 'privileged_approver_id')
    op.drop_column('approval_requests', 'requires_privileged_approval')
    op.drop_column('approval_requests', 'primary_approved_at')
    op.drop_column('approval_requests', 'primary_approver_id')
    # ### end Alembic commands ###
