"""Add user preferences columns

Revision ID: 6df2bb0adaa3
Revises: e224362e51f0
Create Date: 2026-01-11 18:23:13.408087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df2bb0adaa3'
down_revision: Union[str, Sequence[str], None] = 'e224362e51f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_approval_pending'), table_name='approval_requests', postgresql_where="((status = 'PENDING'::approval_status) OR (status = 'PENDING_PRIVILEGED'::approval_status))")
    op.create_index(op.f('ix_control_executions_executed_at'), 'control_executions', ['executed_at'], unique=False)
    op.add_column('users', sa.Column('preferred_theme', sa.String(length=20), server_default='riskhub', nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'preferred_theme')
    op.drop_index(op.f('ix_control_executions_executed_at'), table_name='control_executions')
    op.create_index(op.f('ux_approval_pending'), 'approval_requests', ['resource_type', 'resource_id', 'action_type'], unique=True, postgresql_where="((status = 'PENDING'::approval_status) OR (status = 'PENDING_PRIVILEGED'::approval_status))")
    # ### end Alembic commands ###
