"""add_control_risk_and_execution_tables

Revision ID: 71c378bc4f1c
Revises: b6a0fb5e1e6a
Create Date: 2025-12-25 02:39:54.569839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c378bc4f1c'
down_revision: Union[str, Sequence[str], None] = 'b6a0fb5e1e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_source', sa.String(length=500), nullable=True),
    sa.Column('methodology_reference', sa.String(length=500), nullable=True),
    sa.Column('control_form', sa.String(length=20), nullable=False),
    sa.Column('process_owner_position', sa.String(length=255), nullable=True),
    sa.Column('control_owner_id', sa.Integer(), nullable=True),
    sa.Column('executor_position', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('report_recipient', sa.String(length=500), nullable=True),
    sa.Column('documentation_location', sa.String(length=500), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_owner_id'), 'controls', ['control_owner_id'], unique=False)
    op.create_index(op.f('ix_controls_department_id'), 'controls', ['department_id'], unique=False)
    op.create_index(op.f('ix_controls_name'), 'controls', ['name'], unique=False)
    op.create_index(op.f('ix_controls_status'), 'controls', ['status'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id_code', sa.String(length=50), nullable=False),
    sa.Column('process', sa.String(length=255), nullable=False),
    sa.Column('subprocess', sa.String(length=255), nullable=True),
    sa.Column('risk_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('gross_probability', sa.Integer(), nullable=False),
    sa.Column('gross_impact', sa.Integer(), nullable=False),
    sa.Column('gross_score', sa.Integer(), nullable=False),
    sa.Column('net_probability', sa.Integer(), nullable=False),
    sa.Column('net_impact', sa.Integer(), nullable=False),
    sa.Column('net_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('kri_indicator', sa.String(length=500), nullable=True),
    sa.Column('kri_threshold_green', sa.String(length=255), nullable=True),
    sa.Column('kri_threshold_yellow', sa.String(length=255), nullable=True),
    sa.Column('kri_threshold_red', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_category'), 'risks', ['category'], unique=False)
    op.create_index(op.f('ix_risks_department_id'), 'risks', ['department_id'], unique=False)
    op.create_index(op.f('ix_risks_owner_id'), 'risks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_risks_process'), 'risks', ['process'], unique=False)
    op.create_index(op.f('ix_risks_risk_id_code'), 'risks', ['risk_id_code'], unique=True)
    op.create_index(op.f('ix_risks_risk_type'), 'risks', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('control_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('executed_by_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_scheduled', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_executions_control_id'), 'control_executions', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_executions_executed_by_id'), 'control_executions', ['executed_by_id'], unique=False)
    op.create_table('control_risk_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('effectiveness', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_risk_links_control_id'), 'control_risk_links', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_risk_links_risk_id'), 'control_risk_links', ['risk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_risk_links_risk_id'), table_name='control_risk_links')
    op.drop_index(op.f('ix_control_risk_links_control_id'), table_name='control_risk_links')
    op.drop_table('control_risk_links')
    op.drop_index(op.f('ix_control_executions_executed_by_id'), table_name='control_executions')
    op.drop_index(op.f('ix_control_executions_control_id'), table_name='control_executions')
    op.drop_table('control_executions')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_type'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_id_code'), table_name='risks')
    op.drop_index(op.f('ix_risks_process'), table_name='risks')
    op.drop_index(op.f('ix_risks_owner_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_department_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_category'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_controls_status'), table_name='controls')
    op.drop_index(op.f('ix_controls_name'), table_name='controls')
    op.drop_index(op.f('ix_controls_department_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_control_owner_id'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
