"""add_risk_hub_tables

Revision ID: 74f4ad1b68cb
Revises: e8dfb5de63a6
Create Date: 2026-01-03 11:31:36.858601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f4ad1b68cb'
down_revision: Union[str, Sequence[str], None] = 'e8dfb5de63a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_types_code'), 'risk_types', ['code'], unique=True)
    op.create_table('approval_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approver_roles', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_scenarios_key'), 'approval_scenarios', ['key'], unique=True)
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_config_category'), 'global_config', ['category'], unique=False)
    op.create_index(op.f('ix_global_config_key'), 'global_config', ['key'], unique=True)
    
    # Seed system risk types
    op.execute("""
        INSERT INTO risk_types (code, display_name, description, color, icon, sort_order, is_active, is_system, risk_count)
        VALUES 
        ('strategic', 'Strategic', 'Long-term strategic risks affecting business objectives and market position', '#3b82f6', 'target', 1, true, true, 0),
        ('operational', 'Operational', 'Day-to-day operational risks in processes and procedures', '#f59e0b', 'settings', 2, true, true, 0)
    """)
    
    # Seed global configuration
    op.execute("""
        INSERT INTO global_config (key, value, value_type, category, display_name, description, min_value, max_value, is_editable)
        VALUES 
        ('high_risk_min_net_score', '10', 'int', 'risk_thresholds', 'High Risk Threshold', 'Minimum net score to classify a risk as High Risk', 1, 25, true),
        ('critical_risk_min_net_score', '16', 'int', 'risk_thresholds', 'Critical Risk Threshold', 'Minimum net score to classify a risk as Critical', 1, 25, true),
        ('medium_risk_min_net_score', '5', 'int', 'risk_thresholds', 'Medium Risk Threshold', 'Minimum net score to classify a risk as Medium', 1, 25, true),
        ('require_edit_approval_priority', 'true', 'bool', 'approvals', 'Require Approval for Priority Risk Edits', 'When enabled, editing priority risks requires manager approval', NULL, NULL, true),
        ('require_delete_approval', 'true', 'bool', 'approvals', 'Require Approval for Deletions', 'When enabled, deleting risks/controls/KRIs requires approval', NULL, NULL, true),
        ('secondary_approval_priority', 'true', 'bool', 'approvals', 'Secondary Approval for Priority Risks', 'When enabled, priority risk changes require CRO secondary approval', NULL, NULL, true),
        ('kri_reminder_days_before', '3', 'int', 'notifications', 'KRI Reminder Days', 'Days before KRI deadline to send reminder notification', 1, 14, true),
        ('orphan_escalation_days', '7', 'int', 'notifications', 'Orphan Escalation Days', 'Days before escalating unresolved orphaned items', 1, 30, true)
    """)
    
    # Seed approval scenarios
    op.execute("""
        INSERT INTO approval_scenarios (key, display_name, description, requires_approval, approver_roles)
        VALUES 
        ('risk_delete', 'Delete a Risk', 'Approval required when a risk is requested for deletion', true, '["risk_manager", "cro"]'),
        ('control_delete', 'Delete a Control', 'Approval required when a control is requested for deletion', true, '["risk_manager", "cro"]'),
        ('kri_delete', 'Delete a KRI', 'Approval required when a KRI is requested for deletion', true, '["risk_manager", "cro"]'),
        ('risk_edit_priority', 'Edit Priority Risk', 'Approval required when editing a priority (high-risk) risk', true, '["risk_manager", "cro"]'),
        ('kri_value_submit', 'Submit KRI Value', 'Approval required when submitting a new KRI measurement value', true, '["risk_owner"]'),
        ('control_edit', 'Edit Control (by Owner)', 'Approval required when control owner edits their control', true, '["risk_owner"]')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_config_key'), table_name='global_config')
    op.drop_index(op.f('ix_global_config_category'), table_name='global_config')
    op.drop_table('global_config')
    op.drop_index(op.f('ix_approval_scenarios_key'), table_name='approval_scenarios')
    op.drop_table('approval_scenarios')
    op.drop_index(op.f('ix_risk_types_code'), table_name='risk_types')
    op.drop_table('risk_types')
    # ### end Alembic commands ###
