"""add_role_management_fields

Revision ID: 79d8bd62f3f4
Revises: 74f4ad1b68cb
Create Date: 2026-01-03 12:28:34.405270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d8bd62f3f4'
down_revision: Union[str, Sequence[str], None] = '74f4ad1b68cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'is_system')
    # ### end Alembic commands ###
