"""Add name to risks and description to kris

Revision ID: cfd46dc4cb71
Revises: a999fbda07ce
Create Date: 2026-01-04 10:11:16.996826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd46dc4cb71'
down_revision: Union[str, Sequence[str], None] = 'a999fbda07ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add KRI description column (nullable)
    op.add_column('key_risk_indicators', sa.Column('description', sa.Text(), nullable=True))
    
    # Backfill KRI descriptions with metric_name
    op.execute("""
        UPDATE key_risk_indicators 
        SET description = metric_name 
        WHERE description IS NULL
    """)
    
    # Make KRI description non-nullable
    op.alter_column('key_risk_indicators', 'description', nullable=False)
    
    # Add Risk name column (nullable)
    op.add_column('risks', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_risks_name'), 'risks', ['name'], unique=False)
    
    # Backfill Risk names with process field
    op.execute("""
        UPDATE risks 
        SET name = process 
        WHERE name IS NULL
    """)
    
    # Make Risk name non-nullable
    op.alter_column('risks', 'name', nullable=False)
    
    # Update user timestamp types
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_risks_name'), table_name='risks')
    op.drop_column('risks', 'name')
    op.drop_column('key_risk_indicators', 'description')
    # ### end Alembic commands ###
