from app.services._issue_register.constants import (
    UNKNOWN_CONTROL_LABEL,
    UNKNOWN_DEPARTMENT_LABEL,
    UNKNOWN_EXECUTION_LABEL,
    UNKNOWN_KRI_LABEL,
    UNKNOWN_RISK_LABEL,
    UNKNOWN_USER_LABEL,
    UNKNOWN_VENDOR_LABEL,
)

__all__ = [
    "UNKNOWN_CONTROL_LABEL",
    "UNKNOWN_DEPARTMENT_LABEL",
    "UNKNOWN_EXECUTION_LABEL",
    "UNKNOWN_KRI_LABEL",
    "UNKNOWN_RISK_LABEL",
    "UNKNOWN_USER_LABEL",
    "UNKNOWN_VENDOR_LABEL",
]
