export { DashboardPage } from './DashboardPage';
export { ControlsPage } from './ControlsPage';
export { RisksPage } from './RisksPage';
export { RiskDetailPage } from './RiskDetailPage';
export { RiskNewPage, RiskEditPage } from './RiskForms';
export { DepartmentsPage } from './DepartmentsPage';
export { SettingsPage } from './SettingsPage';
export { HeroPage } from './HeroPage';
export { ControlDetailPage } from './ControlDetailPage';
export * from './ControlForms';
