export { DashboardPage } from './DashboardPage';
export { default as ApprovalsPage } from './ApprovalsPage';
export { ControlsPage } from './ControlsPage';
export { RisksPage } from './RisksPage';
export { RiskDetailPage } from './RiskDetailPage';
export { RiskNewPage, RiskEditPage } from './RiskForms';
export { KRIsPage } from './KRIsPage';
export { KRIDetailPage } from './KRIDetailPage';
export { KRINewPage } from './KRIForms';
export { DepartmentsPage } from './DepartmentsPage';
export { DepartmentDetailPage } from './DepartmentDetailPage';
export { SettingsPage } from './SettingsPage';
export { HeroPage } from './HeroPage';
export { ControlDetailPage } from './ControlDetailPage';
export { AuditTrailPage } from './AuditTrailPage';
export * from './ControlForms';
export { UsersPage } from './UsersPage';
export { UserNewPage } from './UserNewPage';
export { UserDetailPage } from './UserDetailPage';
