"""Centralized non-pagination limits for endpoints (top-N, trend windows, etc.)."""

# Dashboard
DASHBOARD_CONTROL_TREND_WEEKS = 8
DASHBOARD_TREND_MONTHS = 12

DASHBOARD_TOP_CRITICAL_RISKS = 5
DASHBOARD_RECENT_ACTIVITY = 10
DASHBOARD_TOP_DEPARTMENT_EXPOSURE = 5

DASHBOARD_TOP_CRITICAL_VENDORS = 5
DASHBOARD_TOP_OVERDUE_VENDORS = 10
DASHBOARD_TOP_BREACHED_SLAS = 10
DASHBOARD_TOP_MAJOR_INCIDENTS = 10

